<?php
/**
 * Copyright © Landofcoder LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.landofcoder.com | support@landofcoder.com
 */

/**
 * @var $block Lof\SmtpApp\Block\Adminhtml\System\Config\TestButton
 */
?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function ($, alert) {
        window.SmtpAppDebugTest = function(){
            var postData = {form_key: FORM_KEY};

            //global var configForm
            configForm.find('[id^=system_smtpapp]').find(':input').serializeArray().map(function(field){
                var name = field.name.match(/groups\[smtpapp\]?(\[groups\]\[debug\])?\[fields\]\[(.*)\]\[value]/);

                //groups[smtpapp][groups][debug][fields][email][value]
                //groups[smtpapp][fields][password][value]

                if(name && name.length == 3){
                    postData[name[2]] = field.value;
                }
            });

            $.ajax({
                url: '<?php echo $block->getAdminUrl() ?>',
                type: 'post',
                dataType: 'html',
                data: postData,
                showLoader: true
            }).done(function(response) {
                if (typeof response === 'object') {
                    if (response.error) {
                        alert({ title: 'Error', content: response.message });
                    } else if (response.ajaxExpired) {
                        window.location.href = response.ajaxRedirect;
                    }
                } else {
                    alert({
                        title:'',
                        content:response,
                        buttons: []
                    });
                }

            });
        }
    });
</script>

<?php echo $block->getButtonHtml() ?>
